wip: render growth correctly
SlateFoundation/slate-cbl pull request #504
Opened 2020-01-23 21:11 UTC by nbey

- [x] fix: render zero growth correctly
- [ ] prevent rounding of baseline, performance, growth ?

2020-01-25 05:35 UTC, themightychris requested changes
@nbey tests need updating

2020-01-28 00:31 UTC, themightychris commented
@nbey just reran the tests on this one, still failing. b21network/b21-skeleton#6 wouldn't affect this

2020-01-28 02:40 UTC, nbey commented
@themightychris yeah, my bad. I forgot to push to this branch as well.

2020-01-28 04:06 UTC, themightychris approved these changes

2020-01-28 04:06 UTC, merged