refactor: student_demonstrations_growth test [SCHOOL-98]
SlateFoundation/slate-cbl pull request #600
Opened 2021-08-26 21:11 UTC by nbey

refactor: student_demonstrations_growth test
- deprecate json fixtures file

2021-08-26 23:58 UTC, nbey commented on cypress/integration/student_demonstrations_growth.js
> +    it.skip('One full ER plus one additional rating, () => {
Looks like you missed the closing `'` tag.

2021-08-26 23:58 UTC, nbey commented on cypress/integration/student_demonstrations_growth.js
> +    it.skip('One full ER plus one additional rating, less than 50%    ', () => {
Looks like some spaces were pasted at the end of the description

2021-10-13 20:27 UTC, themightychris requested changes
So I've realized that the reason we _need_ the JSON fixtures file is because the `b21-skeleton` repo (and potentially others) have to be able to [override it with different values/cases](https://github.com/b21network/b21-skeleton/tree/develop/cypress/fixtures) because subprojects can potentially change calculations (and b21-skeleton DOES by setting a different growth calculation method)

In #617 I went the other direction to make heavier use of the fixture file, and I think we need to do the same thing here for these tests to pass downstream on `b21-skeleton` where the growth numbers and math have to be different

2021-11-02 20:29 UTC, nbey commented
@themightychris @Camus1859 This PR can be closed -- the original intent for this PR was to deprecate the fixtures file, but we now know that is no longer the route we want to go. There were some minor updates made to the test logic, however I believe the original fixtures file / test should suffice.

2021-11-02 20:29 UTC, closed without merging