test: created new file
SlateFoundation/slate-cbl pull request #625
Opened 2021-11-02 21:26 UTC by Camus1859

2021-11-11 16:02 UTC, themightychris commented
@Camus1859 do you need any support with what you were testing here?

2021-11-11 16:18 UTC, Camus1859 commented
> @Camus1859 do you need any support with what you were testing here?

I didnt mean to add anyone to review it now. @nbey  and I are trying to schedule a time to walk through Sencha in detail and how to use it to grab the necessary elements @themightychris

2021-11-30 18:46 UTC, themightychris commented
@Camus1859 please rename this PR

2021-12-27 19:16 UTC, holly-g commented
@Camus1859 this should be ready to review, can you change the status from `draft`?

2022-01-11 18:16 UTC, themightychris commented on cypress/integration/comptency_dashboard_ratings.js
> +                                .should('have.length', firstCompetency.skillIds.length);
```suggestion
                                cy.get(`tr.cbl-grid-skills-row[data-competency="${firstCompetency.ID}"] [data-student="${studentId}"] li[title="12"]`)
                                    .should('have.length', firstCompetency.skillIds.length);
```

2022-01-11 18:16 UTC, themightychris commented on cypress/integration/comptency_dashboard_ratings.js
> +                                debugger;
```suggestion
```

2022-01-11 18:19 UTC, themightychris commented on cypress/integration/comptency_dashboard_ratings.js
> +                    // const randomCompetency = competencies[competencies.length - Math.floor(Math.random() * (competencies.length - 2) + 2)];
is this here for later? if so let's leave a note why, if not let's delete

2022-01-11 18:20 UTC, themightychris commented on cypress/integration/comptency_dashboard_ratings.js
> +            .click()
```suggestion
            cy.get('#' + rubricSelector.getPicker().id + ' .x-boundlist-item')
                .contains('English Language Arts')
                .click()
```

2022-01-21 00:20 UTC, themightychris requested changes
this test isn't passing right now, I shared some feedback in Slack: https://jarvus.slack.com/archives/C02A7LEFTFD/p1642448769001000

2022-02-22 19:50 UTC, themightychris commented
This is actually looking really good after your recent work @nbey , looks to be failing within the new code:

![Screen Shot 2022-02-22 at 2 49 13 PM](https://user-images.githubusercontent.com/458494/155207987-dca2fa78-ba33-4465-b8f4-2254dfd2ddad.png)

Also seems like there's an intermediate assertion we can add to be getting a better failure in this case

2022-03-10 21:52 UTC, nbey approved these changes

2022-03-10 22:21 UTC, themightychris approved these changes
@nbey @Camus1859 beautiful!

2022-03-10 22:21 UTC, merged