Fixes #740: Drag and drop skill demos
SlateFoundation/slate-cbl pull request #747
Opened 2022-11-28 18:56 UTC by chriscauley

Skill demos can now moved between levels using the mouse.

* Dragging a skill demo collapses all the children of the skill demo (bottom lighter section is empty)
* Dropping it moves between levels
* Dropping on original level has no effect
* State management functionality added to src/store.useUi.js

Demonstration:

[drag-skill-demo.webm](https://user-images.githubusercontent.com/379151/204358189-a6a40f28-cf30-4177-b5bd-02405abddf2d.webm)

2022-11-28 20:26 UTC, tgaffey commented
I was testing dragging and dropping and in the middle of grabbing a rating, I actually forgot where i grabbed it from. is there anything simple we can do to make this a little more obvious? Im thinking of two things. Can the level be highlighted when hovering over it with a rating? Can the icon change if you are hovering over the level it came from? Something visual to make it clear if you try to drop a rating into the initial level.

2022-11-28 20:37 UTC, themightychris commented
> I was testing dragging and dropping and in the middle of grabbing a rating, I actually forgot where i grabbed it from. is there anything simple we can do to make this a little more obvious? Im thinking of two things. Can the level be highlighted when hovering over it with a rating? Can the icon change if you are hovering over the level it came from? Something visual to make it clear if you try to drop a rating into the initial level.

Let's log this in our follow-up ticket for Ryon to apply refined styling

@chriscauley for the scope of this PR can you just make sure the source level container and all the potential destination level containers have distinct CSS classes applied designating something like `.drag-source` and `.drag-target`

2022-11-29 20:12 UTC, themightychris requested changes
add applying drop source or drop target CSS class to every level container in the collapsed view so Ryon can implement visual effects to intuitively differentiate them in a later PR

2022-11-29 21:26 UTC, chriscauley commented
I added `-drag-source` and `-drag-target` classes and made the source element grayed and and 50% opacity. It doesn't look great, but it'll do until we get some design on it.

![image](https://user-images.githubusercontent.com/379151/204651111-fa39ff5d-bd26-4d53-b04c-8ec7daa62107.png)

2022-11-29 21:48 UTC, themightychris approved these changes

2022-11-29 21:50 UTC, merged